### PR TITLE
close button added

### PR DESCRIPTION
**Pull request by paramaDEV**
Hi, this is my first contribution in Hacktoberfest 2020

I just added close button to hide the pop up as you want

### CODE REVIEW

**Comment by amitoj-singh** [comment]
#3

**Comment by amitoj-singh** [comment]
Great work.
Can you please comment in issue. So I can assign you this issue.

**Review by amitoj-singh — COMMENTED** [review]
Can you modify your code to use a fontawesome icon rather using png.

**Comment by paramaDEV** [comment]
> Can you modify your code to use a fontawesome icon rather using png.

Sure i'll do it

**Review by amitoj-singh — COMMENTED** [review]
Thanks for your contribution @paramaDEV 👍

**Pull request merged**
